version: '3.8'

services:
  # API Gateway
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        PROJECT: BloggingPlatform.API
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=BloggingPlatform;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=True
    depends_on:
      - sql-server
      - elasticsearch
      - redis

  # SQL Server
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  # Redis (for caching)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  sqldata:
  esdata: